{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "eco-release.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.externalDatabase.name | default "tetheree_admin" | quote }}
  MYSQL_USER: {{ .Values.externalDatabase.user | default "root" | quote }}
  MYSQL_PASSWORD: {{ .Values.externalDatabase.password | default "" | quote }}
  MYSQL_HOST: {{ include "eco-release.databaseHost" . | quote }}
  MYSQL_PORT: {{ include "eco-release.databasePort" . | quote }}
  SESSION_SECRET: {{ default "" .Values.sessionSecret | quote }}
  NODE_ENV: {{ default "production" .Values.env.NODE_ENV | quote }}
{{- end }}
